### ISSUE TITLE
update pre-commit

### ISSUE THREAD

**Issue by kjappelbaum** [OpenBioML/chemnlp#130]
- pin version
- turn-off autocommit

**Comment by phalem** [comment]
@kjappelbaum  Turn it off, it manipulate file and install doesn't work.

**Comment by kjappelbaum** [comment]
>Turn autocommit off, it manipulate file and install doesn't work.

Thanks for your comment. The answer to this is more nuanced. It will only manipulate the files if you didn't already run the `pre-commit` locally

**Comment by phalem** [comment]
> > Turn autocommit off, it manipulate file and install doesn't work.
> 
> Thanks for your comment. The answer to this is more nuanced. It will only manipulate the files if you didn't already run the `pre-commit` locally

Thanks for replying and for being there. I PR via browser, I was annoying from what happen. I PR data yesterday and it manipulate every time I upload file again and again. It fail it PR due to identifier was 0 and when I take a look on the file I find that it change it's indentation  and added `---` on the top of the file. Some file when I upload it again it work and doesn't change and setup work. I stop PR until now. I was happy that I find the reason behind `\` and `\n` that was in my PR and I hope after you fix this all data can install right. Wait until you finish and thanks again for you attention.
